-- Seed a handful of real Ausbildung employers so the advisor has something to match.
-- Embeddings are left NULL; populated by a one-time script after seed.

insert into public.companies (name, email, address, website, ausbildung_types, description) values
  ('Deutsche Bahn AG',         'ausbildung@deutschebahn.com',    'Potsdamer Platz 2, 10785 Berlin',      'https://www.deutschebahn.com',  array['Fachinformatiker','Industriekaufmann','Mechatroniker','Elektroniker'],      'Größter Ausbilder Deutschlands, über 50 Ausbildungsberufe.'),
  ('Siemens AG',               'ausbildung.de@siemens.com',      'Werner-von-Siemens-Str. 1, 80333 München', 'https://www.siemens.com/de/de', array['Mechatroniker','Industriemechaniker','Fachinformatiker','Elektroniker'],    'Technologiekonzern, starkes duales Studium.'),
  ('BMW Group',                'ausbildung@bmwgroup.com',        'Petuelring 130, 80809 München',        'https://www.bmwgroup.jobs',     array['Industriemechaniker','Fachinformatiker','Kfz-Mechatroniker','Werkzeugmechaniker'], 'Premium-Automobilhersteller mit moderner Ausbildungsakademie.'),
  ('Lufthansa Technik',        'ausbildung.hamburg@lht.dlh.de',  'Weg beim Jäger 193, 22335 Hamburg',    'https://www.lufthansa-technik.com', array['Fluggerätmechaniker','Fluggeraätelektroniker','Industriemechaniker'],       'Instandhaltung von Flugzeugen — spezialisierte Ausbildung.'),
  ('Bosch GmbH',               'ausbildung@de.bosch.com',        'Robert-Bosch-Platz 1, 70839 Gerlingen','https://www.bosch.de',          array['Mechatroniker','Elektroniker','Industriekaufmann','Fachinformatiker'],       'Technik fürs Leben — internationale Ausbildung.'),
  ('SAP SE',                   'ausbildung.de@sap.com',          'Dietmar-Hopp-Allee 16, 69190 Walldorf','https://www.sap.com/germany',   array['Fachinformatiker','Kaufmann für Büromanagement'],                             'Europas größter Softwarekonzern.'),
  ('Allianz Deutschland AG',   'ausbildung@allianz.de',          'Königinstraße 28, 80802 München',     'https://karriere.allianz.de',   array['Kaufmann für Versicherungen','Kaufmann für Büromanagement'],                  'Versicherungs- und Finanzdienstleister.'),
  ('REWE Group',               'ausbildung@rewe-group.com',      'Domstraße 20, 50668 Köln',            'https://www.rewe-group.com',    array['Kaufmann im Einzelhandel','Verkäufer','Fachkraft für Lagerlogistik'],         'Lebensmitteleinzelhandel, bundesweit.'),
  ('Vonovia SE',               'ausbildung@vonovia.de',          'Philippstr. 3, 44803 Bochum',         'https://karriere.vonovia.de',   array['Immobilienkaufmann','Kaufmann für Büromanagement','Anlagenmechaniker SHK'],   'Größte Wohnungsgesellschaft Europas.'),
  ('Charité Berlin',           'ausbildung@charite.de',          'Charitéplatz 1, 10117 Berlin',        'https://www.charite.de',        array['Pflegefachmann','Medizinischer Fachangestellter','Operationstechnischer Assistent'], 'Eine der größten Universitätskliniken Europas.');
