-- Bayern companies seed — 50 Pflegefachmann employers
-- Run in: https://supabase.com/dashboard/project/wuclpdacbgablvtzqmyk/sql/new

INSERT INTO companies (name, email, ausbildung_types, bundesland, region, address) VALUES
  ('München Klinik', 'ausbildung@muenchen-klinik.de', '{Pflegefachmann}', 'Bayern', 'München', 'Thalkirchner Str. 48, 80337 München'),
  ('LMU Klinikum München', 'pflegedirektion@med.uni-muenchen.de', '{Pflegefachmann}', 'Bayern', 'München', 'Marchioninistraße 15, 81377 München'),
  ('Klinikum rechts der Isar', 'personalabteilung@mri.tum.de', '{Pflegefachmann}', 'Bayern', 'München', 'Ismaninger Str. 22, 81675 München'),
  ('Krankenhaus Barmherzige Brüder München', 'personal@barmherzige-muenchen.de', '{Pflegefachmann}', 'Bayern', 'München', 'Romanstraße 93, 80639 München'),
  ('Schön Klinik München Harlaching', 'karriere@schoen-klinik.de', '{Pflegefachmann}', 'Bayern', 'München', 'Harlachinger Str. 51, 81547 München'),
  ('Helios Klinikum München West', 'karriere.muenchen@helios-gesundheit.de', '{Pflegefachmann}', 'Bayern', 'München', 'Steinerweg 5, 81241 München'),
  ('Artemed Kliniken München', 'info@artemed.de', '{Pflegefachmann}', 'Bayern', 'München', 'Am Isarkanal 30, 81379 München'),
  ('Rotkreuzklinikum München', 'bewerbung@rotkreuzklinikum-muenchen.de', '{Pflegefachmann}', 'Bayern', 'München', 'Nymphenburger Str. 163, 80634 München'),
  ('Augustinum Klinik München', 'personal@augustinum.de', '{Pflegefachmann}', 'Bayern', 'München', 'Wolkerweg 16, 81375 München'),
  ('Universitätsklinikum Erlangen', 'personalabteilung@uk-erlangen.de', '{Pflegefachmann}', 'Bayern', 'Erlangen', 'Krankenhausstraße 12, 91054 Erlangen'),
  ('Klinikum Nürnberg', 'bewerbung@klinikum-nuernberg.de', '{Pflegefachmann}', 'Bayern', 'Nürnberg', 'Prof.-Ernst-Nathan-Str. 1, 90419 Nürnberg'),
  ('Universitätsklinikum Würzburg', 'personal@ukw.de', '{Pflegefachmann}', 'Bayern', 'Würzburg', 'Josef-Schneider-Str. 2, 97080 Würzburg'),
  ('Klinikum Augsburg', 'bewerbung@uk-augsburg.de', '{Pflegefachmann}', 'Bayern', 'Augsburg', 'Stenglinstraße 2, 86156 Augsburg'),
  ('Klinikum Ingolstadt', 'bewerbung@klinikum-ingolstadt.de', '{Pflegefachmann}', 'Bayern', 'Ingolstadt', 'Krumenauerstraße 25, 85049 Ingolstadt'),
  ('Klinikum Passau', 'personal@klinikum-passau.de', '{Pflegefachmann}', 'Bayern', 'Passau', 'Innstraße 76, 94032 Passau'),
  ('Klinikum Landshut', 'personalabteilung@klinikum-landshut.de', '{Pflegefachmann}', 'Bayern', 'Landshut', 'Robert-Koch-Str. 1, 84034 Landshut'),
  ('Klinikum Rosenheim', 'personal@ro-med.de', '{Pflegefachmann}', 'Bayern', 'Rosenheim', 'Pettenkoferstraße 10, 83022 Rosenheim'),
  ('Klinikum Kempten', 'bewerbung@klinikum-kempten.de', '{Pflegefachmann}', 'Bayern', 'Kempten', 'Robert-Weixler-Str. 50, 87439 Kempten'),
  ('Klinikum Memmingen', 'personal@klinikum-memmingen.de', '{Pflegefachmann}', 'Bayern', 'Memmingen', 'Bismarckstraße 23, 87700 Memmingen'),
  ('München Klinik Bildungscampus', 'bildungscampus@muenchen-klinik.de', '{Pflegefachmann}', 'Bayern', 'München', 'Kraepelinstraße 18, 80804 München'),
  ('Staatliche Berufsfachschule für Pflege am LMU Klinikum', 'pflegeschule@med.uni-muenchen.de', '{Pflegefachmann}', 'Bayern', 'München', 'Heinz-Goerke-Straße 5, 81377 München'),
  ('Berufsfachschule für Pflege Maria Regina', 'pflegeschule@maria-theresia-klinik.de', '{Pflegefachmann}', 'Bayern', 'München', 'Thalkirchner Straße 22, 80337 München'),
  ('Bayerische Pflegeakademie', 'info@bayerische-pflegeakademie.de', '{Pflegefachmann}', 'Bayern', 'München', 'Edelsbergstraße 6, 80686 München'),
  ('Klinikum Dritter Orden München', 'personal@dritter-orden.de', '{Pflegefachmann}', 'Bayern', 'München', 'Menzinger Str. 44, 80638 München'),
  ('Städtisches Klinikum München Schwabing', 'karriere@muenchen-klinik.de', '{Pflegefachmann}', 'Bayern', 'München', 'Kölner Platz 1, 80804 München'),
  ('Städtisches Klinikum München Neuperlach', 'karriere@muenchen-klinik.de', '{Pflegefachmann}', 'Bayern', 'München', 'Oskar-Maria-Graf-Ring 51, 81737 München'),
  ('Städtisches Klinikum München Bogenhausen', 'karriere@muenchen-klinik.de', '{Pflegefachmann}', 'Bayern', 'München', 'Englschalkinger Straße 77, 81925 München'),
  ('Caritas Altenheim St. Josef München', 'info@caritasmuenchen.de', '{Pflegefachmann}', 'Bayern', 'München', 'Luise-Kiesselbach-Platz 2, 81377 München'),
  ('BRK Seniorenwohnen München', 'info@kvmucl.brk.de', '{Pflegefachmann}', 'Bayern', 'München', 'Perchtinger Straße 10, 81379 München'),
  ('Diakoneo Pflege Bayern', 'info@diakoneo.de', '{Pflegefachmann}', 'Bayern', 'Bayern', 'Wilhelm-Löhe-Straße 16, 91564 Neuendettelsau'),
  ('Linemed Bayern GmbH', 'info@linimed-bayern.de', '{Pflegefachmann}', 'Bayern', 'Bayern', 'Hanauer Straße 56, 80992 München'),
  ('Klinikum Freising', 'info@klinikum-freising.de', '{Pflegefachmann}', 'Bayern', 'Freising', 'Alois-Steinecker-Str. 18, 85354 Freising'),
  ('Klinikum Dachau', 'personal@helios-gesundheit.de', '{Pflegefachmann}', 'Bayern', 'Dachau', 'Krankenhausstraße 15, 85221 Dachau'),
  ('Klinikum Fürstenfeldbruck', 'info@klinikum-ffb.de', '{Pflegefachmann}', 'Bayern', 'Fürstenfeldbruck', 'Dachauer Str. 33, 82256 Fürstenfeldbruck'),
  ('Klinikum Erding', 'personal@klinikum-erding.de', '{Pflegefachmann}', 'Bayern', 'Erding', 'Bajuwarenstraße 5, 85435 Erding'),
  ('Klinikum Starnberg', 'personal@klinikum-starnberg.de', '{Pflegefachmann}', 'Bayern', 'Starnberg', 'Oßwaldstraße 1, 82319 Starnberg'),
  ('Klinikum Garmisch-Partenkirchen', 'personal@klinikum-gap.de', '{Pflegefachmann}', 'Bayern', 'Garmisch', 'Auenstraße 6, 82467 Garmisch-Partenkirchen'),
  ('Klinikum Traunstein', 'personal@kliniken-sob.de', '{Pflegefachmann}', 'Bayern', 'Traunstein', 'Cuno-Niggl-Straße 3, 83278 Traunstein'),
  ('Klinikum Berchtesgadener Land', 'info@kliniken-bgl.de', '{Pflegefachmann}', 'Bayern', 'Bad Reichenhall', 'Riedelstraße 5, 83435 Bad Reichenhall'),
  ('Klinikum Altötting', 'personal@innklinikum.de', '{Pflegefachmann}', 'Bayern', 'Altötting', 'Vinzenz-von-Paul-Straße 10, 84503 Altötting'),
  ('Klinikum Mühldorf am Inn', 'personal@innklinikum.de', '{Pflegefachmann}', 'Bayern', 'Mühldorf', 'Krankenhausstraße 1, 84453 Mühldorf am Inn'),
  ('Klinikum Deggendorf', 'personal@klinikum-deggendorf.de', '{Pflegefachmann}', 'Bayern', 'Deggendorf', 'Perlasberger Straße 41, 94469 Deggendorf'),
  ('Klinikum Straubing', 'personal@klinikum-straubing.de', '{Pflegefachmann}', 'Bayern', 'Straubing', 'St.-Elisabeth-Straße 23, 94315 Straubing'),
  ('Klinikum Regensburg', 'bewerbung@ukr.de', '{Pflegefachmann}', 'Bayern', 'Regensburg', 'Franz-Josef-Strauß-Allee 11, 93053 Regensburg'),
  ('Klinikum Amberg', 'personal@klinikum-amberg.de', '{Pflegefachmann}', 'Bayern', 'Amberg', 'Mariahilfbergweg 7, 92224 Amberg'),
  ('Klinikum Weiden', 'personal@kliniken-nordoberpfalz.de', '{Pflegefachmann}', 'Bayern', 'Weiden', 'Söllnerstraße 16, 92637 Weiden in der Oberpfalz'),
  ('Klinikum Bayreuth', 'bewerbung@klinikum-bayreuth.de', '{Pflegefachmann}', 'Bayern', 'Bayreuth', 'Preuschwitzer Straße 101, 95445 Bayreuth'),
  ('Klinikum Bamberg', 'personal@sozialstiftung-bamberg.de', '{Pflegefachmann}', 'Bayern', 'Bamberg', 'Buger Straße 80, 96049 Bamberg'),
  ('Klinikum Coburg', 'personal@regiomed-kliniken.de', '{Pflegefachmann}', 'Bayern', 'Coburg', 'Ketschendorfer Straße 33, 96450 Coburg'),
  ('Klinik Bavaria GmbH & Co. KG', 'info@klinik-bavaria.de', '{Pflegefachmann}', 'Bayern', 'Bad Kissingen', 'Von-der-Tann-Str. 18-22, 97688 Bad Kissingen'),
  ('Senioren- und Pflegeheim Vincentinum München', 'info@vincentinum.de', '{Pflegefachmann}', 'Bayern', 'München', 'Oettingenstraße 16, 80538 München'),
  ('Vitanas Senioren Centrum Am Partnachplatz', 'info@vitanas.de', '{Pflegefachmann}', 'Bayern', 'München', 'Albert-Roßhaupter-Str. 90, 81369 München')
;
