#!/usr/bin/env bash
# Bundle all agent prompts (.md) into a TypeScript module so Supabase
# Edge Functions pick them up as part of the function bundle. The CLI
# (Node) still reads the raw .md files; this generator is purely for
# the Deno deploy path.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

SRC_DIR="supabase/functions/_prompts"
OUT_FILE="supabase/functions/_shared/prompts-data.ts"

{
  echo "// AUTO-GENERATED by scripts/build-prompts.sh — do not edit by hand."
  echo "// Source: supabase/functions/_prompts/*.md"
  echo ""
  echo "export const PROMPTS: Record<string, string> = {"
  for f in "$SRC_DIR"/*.md; do
    name="$(basename "$f" .md)"
    # Escape backticks and ${ for template literals.
    body="$(sed -e 's/\\/\\\\/g' -e 's/`/\\`/g' -e 's/\${/\\${/g' "$f")"
    echo "  \"$name\": \`$body\`,"
  done
  echo "};"
} > "$OUT_FILE"

echo "✅ Wrote $OUT_FILE ($(wc -l < "$OUT_FILE") lines)."
